### PR TITLE
Creating Documentation for Dynamic Forms Module

### PR DESCRIPTION
**Pull request by phillipsj**
Created documentation for Dynamic Forms module, based it on the
documentation for the Custom Forms module. Added as close to the same screenshots as I could, and I updated the index and remove it from the suggested topics.

Submitted on behalf of Radio Systems Corporation

### CODE REVIEW

**Comment by phillipsj** [comment]
@rtpHarry  I am going to go through and fix these typos.  I did not remove Orchard Layouts, if you look at the commit below due to remove Orchard.DynamicForms it just shifted the Orchard.Layouts.

**Comment by phillipsj** [comment]
So I fixed all of the typos discovered.  Dynamic Forms are had to explain because you do have to recreate the form for your content type, it is not a lot like Custom Forms in that respect.  Maybe it is, but the walkthrough on IDeliverable's blog shows having to create the form from scratch instead of having it created by the selected content type.

Also, I did start with the Custom Forms documentation since I wanted to be as familiar to users and that except for details the concept is the same.

**Comment by phillipsj** [comment]
@rtpHarry I totally agree and I am more than happy to make those changes.  I was just trying to keep it in the style of the previous documentation, I was just trying to get some documentation together since it is better than no documentation.  I will try to see if I have the time this weekend to make those changes.

**Comment by abhishekluv** [comment]
Great work @phillipsj I'll wait for @rtpHarry to give me a :+1:  signal to merge this PR as he has already read the commits and changes made by you. :)

**Comment by rtpHarry** [comment]
@phillipsj Great tutorial! I've followed it all the way though with a fresh copy of Orchard and everything checks out. 

I was getting confused in my earlier comment when I said some stuff came from the CustomForms. To start off with I was just following along in my head but got confused and thought we were making the form a second time.

If you don't find the time to make the last few amendments /typos over the weekend the please feel free to add a comment on here tagging me in and I'll finish it off. I don't want your great contribution to get stuck in limbo over a few last tweaks :)

**Comment by phillipsj** [comment]
I should be able to get those knocked out this weekend.

**Comment by rtpHarry** [comment]
:+1:

**Comment by phillipsj** [comment]
@rtpHarry  So I fixed the basic issues.  I will work on making it more of a tutorial like experience soon.

**Comment by rtpHarry** [comment]
@abhishekluv I think we should merge the pull request now as the basic typos have all been resolved. 

Jamie can open a new pull request in the future for any further amends but there's no point in letting this sit in limbo.

**Pull request merged**
