### PR TITLE
Added a page dedicated to Logging in Orchard

### PR DESCRIPTION
**Pull request by Elindie**
Added a page documenting the usage of ILogger and log4net.
Updated link to Logger source code on github

### CODE REVIEW

**Comment by rtpHarry** [comment]
Something has got messed up with this pull request, it looks like you picked the wrong branch as it's trying to merge into the "sebros/accept-pr" branch.

**Comment by rtpHarry** [comment]
It doesn't seem to include your ilogger article either. I think you probably need to just close this PR and then have another go

**Comment by Elindie** [comment]
Thanks for the heads up, I'll go ahead and do that.

**Comment by Elindie** [comment]
Hi Harry, I've tried to create a pull request a few times and am having a bit of trouble. Would you mind giving me a high level explanation of how I need to do this? I've read the docs, but clearly I'm missing something critical here.

**Comment by rtpHarry** [comment]
hey, yeah no problem. What seems to be happening is you are on the wrong branch because the PR is going into the `sebros/accept-pr` branch:

image

That was just an old branch that was used for one thing ages back. It looks like you're actually working off a much new branch because its trying to merge in the hundreds of commits on master that have happened since that old branch was first created.

When you create the PR you want the BASE to be the OrchardDocs Master branch:

image

And then the compare should be the branch you have made your changes to.

See if that gets you any further, if not I'm happy to use remote support software and we can share screens and figure out whats going on :)

**Comment by Elindie** [comment]
I'll give that a shot, thanks for the snappy reply!

**Pull request closed without merging**
